# Database.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  namespace: mongo
spec:
  selector:
    matchLabels:
      app: my-db
  replicas: 1
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db
        image: mongo:4.4-focal
        envFrom:
        - secretRef:
            name: my-db-secret
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongo-data-volume
        configMap:
          name: mongo-init-js
---
# Database init script.
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-js
  namespace: mongo
data:
  data.js: |
    db = db.getSiblingDB('product-service');

    db.createCollection('products');

    db.products.insertMany(
        [
            {
                "name":"iphone",
                "price": "1200"
            },
            {
                "name":"ipad",
                "price": "800"
            },
            {
                "name":"mac",
                "price": "3000"
            }                
        ]
    )
---
# Database Secrets.
apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
  namespace: mongo
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
---
# Port Forward to DB.
apiVersion: v1
kind: Service
metadata:
  name: my-db-port-service
  namespace: mongo
spec:
  selector:
    app: my-db
  ports:
  - port: 27017
    targetPort: 27017
---
# GUI.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gui
  namespace: mongo
spec:
  selector:
    matchLabels:
      app: my-gui
  replicas: 1
  template:
    metadata:
      labels:
        app: my-gui
    spec:
      containers:
      - name: my-gui
        image: mongo-express:1.0.0-alpha.4
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: my-gui-secret
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: my-db-port-service
---
# GUI Secrets.
apiVersion: v1
kind: Secret
metadata:
  name: my-gui-secret
  namespace: mongo
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=
  # ME_CONFIG_MONGODB_SERVER: bW9uZ28=
---
# Port Forward From outside to GUI.
apiVersion: v1
kind: Service
metadata:
  name: my-gui-port-service
  namespace: mongo
spec:
  type: NodePort
  selector:
    app: my-gui
  ports:
  - port: 8081
    targetPort: 8081