apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *" # crontab based schedule
  successfulJobsHistoryLimit: 3  # Set the number of successful jobs to retain
  failedJobsHistoryLimit: 3      # Set the number of failed jobs to retain
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
