apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *" # crontab based schedule
  successfulJobsHistoryLimit: 3  # Set the number of successful jobs to retain
  failedJobsHistoryLimit: 3      # Set the number of failed jobs to retain
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            volumeMounts:
            - name: ananda-api-config-txt-vol
              mountPath: /code/config/
          volumes:
          - name: ananda-api-config-txt-vol
            secret:
              secretName: ananda-api-config-secret
